name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          brew install python-tk@3.11
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/ || echo "No tests found"

      - name: Build macOS app
        run: |
          pip install py2app
          python setup.py py2app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: dist/*.app
